FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore ./SampleModule/SampleModule.csproj

COPY . ./
RUN dotnet publish ./SampleModule/SampleModule.csproj -c Release -o out

FROM microsoft/dotnet:2.1-runtime-stretch-slim
WORKDIR /app
COPY --from=build-env /app/SampleModule/out ./

RUN apt-get update && apt-get install -y iputils-ping

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "SampleModule.dll"]